version: '3.8'

services:
  app:
    image: yourusername/weather-api:latest
    environment:
      - OPENWEATHER_API_KEY=your_openweather_api_key
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --interval 30 
